app_id: 5D3E10A6-6E29-4F1D-9B7E-81F21A73D4C2
publisher: RenYiChun
publisher_url: https://github.com/RenYiChun/hiddify-app
display_name: Hiddify Custom
create_desktop_icon: true
install_dir_name: "{autopf64}\\Hiddify Custom"
setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - ar
  - en
  - es
  - fr
  - pt
  - ru
  - tr
script_template: inno_setup.sas
